// Generated by scripts/generate-responsive-faction-portraits.mjs
export const FACTION_PORTRAIT_DERIVATIVES: Readonly<Record<string, readonly { src: string; width: number }[]>> = {
  "acontecimento": [
    {
      "src": "/faction-portraits/optimized/acontecimento.320.b45b6cfea7e8.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/acontecimento.640.b101e8b3c02f.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/acontecimento.960.ad84a856f7fe.webp",
      "width": 960
    }
  ],
  "aleph": [
    {
      "src": "/faction-portraits/optimized/aleph.320.abd0f8a4f0b6.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/aleph.640.e82635879dd9.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/aleph.960.807680ebfe93.webp",
      "width": 960
    }
  ],
  "ariadna": [
    {
      "src": "/faction-portraits/optimized/ariadna.320.3b5d02f18fe0.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/ariadna.640.a0970acf7483.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/ariadna.960.e51ce19ecaf0.webp",
      "width": 960
    }
  ],
  "bakunin": [
    {
      "src": "/faction-portraits/optimized/bakunin.320.30628d5c89cd.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/bakunin.640.40b06d2acba4.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/bakunin.960.4cf73740ba08.webp",
      "width": 960
    }
  ],
  "caledonian-highlander-army": [
    {
      "src": "/faction-portraits/optimized/caledonian-highlander-army.320.d3080851008c.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/caledonian-highlander-army.640.daa36d552487.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/caledonian-highlander-army.960.022e18a121c6.webp",
      "width": 960
    }
  ],
  "combined-army": [
    {
      "src": "/faction-portraits/optimized/combined-army.320.3bd9f3e4808c.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/combined-army.640.74fc6883e171.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/combined-army.960.3a4533fd97fe.webp",
      "width": 960
    }
  ],
  "corregidor": [
    {
      "src": "/faction-portraits/optimized/corregidor.320.a1b448215ec6.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/corregidor.640.6256d15224db.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/corregidor.960.e1c6f94d36b1.webp",
      "width": 960
    }
  ],
  "dahshat-company": [
    {
      "src": "/faction-portraits/optimized/dahshat-company.320.2f1fd3d58808.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/dahshat-company.640.597abdb97773.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/dahshat-company.960.8ac38881e19f.webp",
      "width": 960
    }
  ],
  "druze-bayram-security": [
    {
      "src": "/faction-portraits/optimized/druze-bayram-security.320.ac48a7241c0b.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/druze-bayram-security.640.b35208e48816.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/druze-bayram-security.960.e19ef847e175.webp",
      "width": 960
    }
  ],
  "frrm": [
    {
      "src": "/faction-portraits/optimized/frrm.320.9d792830183e.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/frrm.640.05f697e6f353.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/frrm.960.dccce02e49fe.webp",
      "width": 960
    }
  ],
  "haqqislam": [
    {
      "src": "/faction-portraits/optimized/haqqislam.320.a27824dfd059.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/haqqislam.640.62e08fa4a56f.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/haqqislam.960.2eb120ef020c.webp",
      "width": 960
    }
  ],
  "hassassin-bahram": [
    {
      "src": "/faction-portraits/optimized/hassassin-bahram.320.395e74577578.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/hassassin-bahram.640.bffad99edbe7.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/hassassin-bahram.960.3dd9e9ca1717.webp",
      "width": 960
    }
  ],
  "ikari-company": [
    {
      "src": "/faction-portraits/optimized/ikari-company.320.b326e5d3ec23.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/ikari-company.640.f88a75a628c8.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/ikari-company.960.748027d8e8c5.webp",
      "width": 960
    }
  ],
  "imperial-service": [
    {
      "src": "/faction-portraits/optimized/imperial-service.320.8f4eeb2b2365.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/imperial-service.640.b2cdcbf69c43.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/imperial-service.960.8b0932665f10.webp",
      "width": 960
    }
  ],
  "invincible-army": [
    {
      "src": "/faction-portraits/optimized/invincible-army.320.ded09abdab09.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/invincible-army.640.7ebb87ff8a34.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/invincible-army.960.a770b0044d49.webp",
      "width": 960
    }
  ],
  "jsa": [
    {
      "src": "/faction-portraits/optimized/jsa.320.2cacef562ef3.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/jsa.640.4279d88f1540.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/jsa.960.dd887dcc764d.webp",
      "width": 960
    }
  ],
  "kestrel-colonial-force": [
    {
      "src": "/faction-portraits/optimized/kestrel-colonial-force.320.71ed60c03d94.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/kestrel-colonial-force.640.87a36e040dab.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/kestrel-colonial-force.960.16f35faaec5b.webp",
      "width": 960
    }
  ],
  "kosmoflot": [
    {
      "src": "/faction-portraits/optimized/kosmoflot.320.dc6c2bfd552d.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/kosmoflot.640.6060d25d5321.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/kosmoflot.960.d1f852da99b2.webp",
      "width": 960
    }
  ],
  "military-orders": [
    {
      "src": "/faction-portraits/optimized/military-orders.320.d50589037e0e.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/military-orders.640.77c0fde151dd.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/military-orders.960.6d8bcdbf3bb0.webp",
      "width": 960
    }
  ],
  "morats": [
    {
      "src": "/faction-portraits/optimized/morats.320.4f81246383a1.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/morats.640.caa155c326f2.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/morats.960.1aa16be6ab76.webp",
      "width": 960
    }
  ],
  "neoterra": [
    {
      "src": "/faction-portraits/optimized/neoterra.320.e6bbd7d6e5ee.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/neoterra.640.fefefeae3f81.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/neoterra.960.15e60b7d59b7.webp",
      "width": 960
    }
  ],
  "next-wave": [
    {
      "src": "/faction-portraits/optimized/next-wave.320.cdea90fc0a89.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/next-wave.640.63687f726dff.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/next-wave.960.6610022ff9b6.webp",
      "width": 960
    }
  ],
  "nomads": [
    {
      "src": "/faction-portraits/optimized/nomads.320.2de7136d6776.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/nomads.640.e101c0c74fc1.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/nomads.960.47d23bd14eaf.webp",
      "width": 960
    }
  ],
  "o-12": [
    {
      "src": "/faction-portraits/optimized/o-12.320.84209d9ab9d1.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/o-12.640.3611d3b092af.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/o-12.960.9ab071c3ff76.webp",
      "width": 960
    }
  ],
  "oban": [
    {
      "src": "/faction-portraits/optimized/oban.320.54ec804554e9.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/oban.640.04baee68cd23.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/oban.960.48da08b119a8.webp",
      "width": 960
    }
  ],
  "onyx-contact-force": [
    {
      "src": "/faction-portraits/optimized/onyx-contact-force.320.d0d0fd288168.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/onyx-contact-force.640.e6fa72afa7d4.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/onyx-contact-force.960.e9b88e4fd8eb.webp",
      "width": 960
    }
  ],
  "operations-subsection": [
    {
      "src": "/faction-portraits/optimized/operations-subsection.320.e1a63a5360e8.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/operations-subsection.640.c86aee1bec48.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/operations-subsection.960.a9a6948c9d56.webp",
      "width": 960
    }
  ],
  "panoceania": [
    {
      "src": "/faction-portraits/optimized/panoceania.320.26d4020d7523.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/panoceania.640.a7fcf2d6aece.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/panoceania.960.705964100174.webp",
      "width": 960
    }
  ],
  "qapu-khalqi": [
    {
      "src": "/faction-portraits/optimized/qapu-khalqi.320.a90b7483dd70.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/qapu-khalqi.640.e01d7ff0f2a5.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/qapu-khalqi.960.f6ff1d666f98.webp",
      "width": 960
    }
  ],
  "ramah-taskforce": [
    {
      "src": "/faction-portraits/optimized/ramah-taskforce.320.d8e2c2f043e1.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/ramah-taskforce.640.07788f8c46b7.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/ramah-taskforce.960.01278eb81edf.webp",
      "width": 960
    }
  ],
  "shasvastii": [
    {
      "src": "/faction-portraits/optimized/shasvastii.320.80550465fce8.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/shasvastii.640.f789ae1a5c92.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/shasvastii.960.b7fd690c0d94.webp",
      "width": 960
    }
  ],
  "shindenbutai": [
    {
      "src": "/faction-portraits/optimized/shindenbutai.320.feb0914e1bf0.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/shindenbutai.640.9caea4523ca6.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/shindenbutai.960.af8569907774.webp",
      "width": 960
    }
  ],
  "starco": [
    {
      "src": "/faction-portraits/optimized/starco.320.480ef85cf7e0.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/starco.640.90910ecbb69a.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/starco.960.cc79a7e4f278.webp",
      "width": 960
    }
  ],
  "starmada": [
    {
      "src": "/faction-portraits/optimized/starmada.320.15aa4963faae.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/starmada.640.147a117b5d46.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/starmada.960.d4de44967ecc.webp",
      "width": 960
    }
  ],
  "steel-phalanx": [
    {
      "src": "/faction-portraits/optimized/steel-phalanx.320.1cf946d9ec49.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/steel-phalanx.640.db11e220b372.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/steel-phalanx.960.c8bb8113f66d.webp",
      "width": 960
    }
  ],
  "tartary-army-corps": [
    {
      "src": "/faction-portraits/optimized/tartary-army-corps.320.7dac495d5c8e.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/tartary-army-corps.640.11b34b5a669b.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/tartary-army-corps.960.9fb6e2b42dd3.webp",
      "width": 960
    }
  ],
  "tohaa": [
    {
      "src": "/faction-portraits/optimized/tohaa.320.244e98b89983.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/tohaa.640.b745ead00e29.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/tohaa.960.fa72bfa04689.webp",
      "width": 960
    }
  ],
  "torchlight-brigade": [
    {
      "src": "/faction-portraits/optimized/torchlight-brigade.320.c7ad6a5fa91d.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/torchlight-brigade.640.fd4058706573.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/torchlight-brigade.960.b74a8d35fcb3.webp",
      "width": 960
    }
  ],
  "tunguska": [
    {
      "src": "/faction-portraits/optimized/tunguska.320.2a3292c66efe.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/tunguska.640.59df08f72b74.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/tunguska.960.98a8651d818b.webp",
      "width": 960
    }
  ],
  "usariadna": [
    {
      "src": "/faction-portraits/optimized/usariadna.320.88d98574dc07.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/usariadna.640.713e76566016.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/usariadna.960.49937b6671c5.webp",
      "width": 960
    }
  ],
  "varuna": [
    {
      "src": "/faction-portraits/optimized/varuna.320.d01ea2f597f6.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/varuna.640.b9c7a546942a.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/varuna.960.b37a063ba5eb.webp",
      "width": 960
    }
  ],
  "white-banner": [
    {
      "src": "/faction-portraits/optimized/white-banner.320.3fb71b95dd62.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/white-banner.640.ff5baf5b13ac.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/white-banner.960.266d66f8df4f.webp",
      "width": 960
    }
  ],
  "white-company": [
    {
      "src": "/faction-portraits/optimized/white-company.320.27bd9b83c1db.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/white-company.640.f654ba76e768.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/white-company.960.6a7395794140.webp",
      "width": 960
    }
  ],
  "winter-for": [
    {
      "src": "/faction-portraits/optimized/winter-for.320.c655c85d1915.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/winter-for.640.1cdb179d64ad.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/winter-for.960.4d338c98af34.webp",
      "width": 960
    }
  ],
  "yu-jing": [
    {
      "src": "/faction-portraits/optimized/yu-jing.320.15231a6c4ca1.webp",
      "width": 320
    },
    {
      "src": "/faction-portraits/optimized/yu-jing.640.7734539af96c.webp",
      "width": 640
    },
    {
      "src": "/faction-portraits/optimized/yu-jing.960.3a97c9d747fb.webp",
      "width": 960
    }
  ]
} as const
